### PR TITLE
Show ELF games as separate counter

### PR DESCRIPTION
**Pull request by rchs819**
- calculated by summing `game_count` from `networks`
- added past 24 hours / 1 hour stats for ELF games

On server start
```
206 LZ games, 2 ELF games.
```

On page
```
206 total LZ selfplay games, (0 in past 24 hours, 0 in past hour).
2 total ELF selfplay games, (0 in past 24 hours, 0 in past hour).
```

### CODE REVIEW

**Comment by roy7** [comment]
Hmm.

http://zero.sjeng.org/ seems to just hang. Log shows things are working. But I'll bring prior server.js back up.

**Comment by roy7** [comment]
My guess is the change to the count mongo command is perhaps no longer able to use indexes or something? But as a sum it should be walking the whole collection anyway. I'm just not really sure. But web site wouldn't reply, no errors in log file.

**Comment by roy7** [comment]
No, when I do it in console the result is instant.

> { "_id" : { "type" : "ELF" }, "total" : 2231 }
> { "_id" : { "type" : "LZ" }, "total" : 7259277 }

**Comment by roy7** [comment]
Found it. In games table it is "networkhash" not "hash". (networkhash and sgfhash both exist for a game in games). So it's doing full table scan of games collection on each query when making the HTML. Will fix.

**Comment by roy7** [comment]
Ah yes.

> db.games.find({ networkhash: { $ne: "62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9" } }).count()

Does a table scan. Takes a while.

**Comment by roy7** [comment]
```
> db.games.explain().find({ networkhash: { $ne: "62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9" } }).count()
{
        "queryPlanner" : {
                "plannerVersion" : 1,
                "namespace" : "test.games",
                "indexFilterSet" : false,
                "parsedQuery" : {
                        "$nor" : [
                                {
                                        "networkhash" : {
                                                "$eq" : "62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9"
                                        }
                                }
                        ]
                },
                "winningPlan" : {
                        "stage" : "COUNT",
                        "inputStage" : {
                                "stage" : "FETCH",
                                "inputStage" : {
                                        "stage" : "IXSCAN",
                                        "keyPattern" : {
                                                "networkhash" : 1
                                        },
                                        "indexName" : "networkhash_1",
                                        "isMultiKey" : false,
                                        "multiKeyPaths" : {
                                                "networkhash" : [ ]
                                        },
                                        "isUnique" : false,
                                        "isSparse" : false,
                                        "isPartial" : false,
                                        "indexVersion" : 2,
                                        "direction" : "forward",
                                        "indexBounds" : {
                                                "networkhash" : [
                                                        "[MinKey, \"62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9\")",
                                                        "(\"62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9\", MaxKey]"
                                                ]
                                        }
                                }
                        }
                },
                "rejectedPlans" : [ ]
        },
        "serverInfo" : {
                "host" : "sjeng.org",
                "port" : 27017,
                "version" : "3.4.14",
                "gitVersion" : "fd954412dfc10e4d1e3e2dd4fac040f8b476b268"
        },
        "ok" : 1
}

```

**Comment by rchs819** [comment]
I would prefer not to add new index.

I'll try working with `$eq` and probably write a script for database benchmark comparison

**Pull request merged**
