### PR TITLE
put `elograph.json` in `cachematches` cache

### PR DESCRIPTION
**Pull request by rchs819**
Enhancement for #3 Cache the elograph.json result 

- Refactored elograph.json database calls
- database result is now cached in `cachematches`

@roy7 Do we have a test environment? I don't have data to test the changes.

### CODE REVIEW

**Comment by roy7** [comment]
I'm afraid we don't. One can import the mongo keys from the github but there's no test data to populate with atm. I should maybe dump a few rows of every table and put it in the github as test data. I think you're only the second person to set the server up and work on it though (not including me). :)

**Comment by rchs819** [comment]
Yes please, a small data dump will be a good starting point.

**Comment by roy7** [comment]
Starting to test this one out.

ERROR data/elograph.json: ReferenceError: totalgames is not defined

Will see if I can fix that up.

**Comment by roy7** [comment]
Looks like you cached the db info but then calculate the rest each time. I'll try expanding the cache wrapper around all of it, so nothing is done each time. The whole final result will be cached. This way totalgames also remains in proper scope.

**Comment by roy7** [comment]
Ok you can see the working change I made in https://github.com/gcp/leela-zero-server/tree/rchs819-enhancement/cache-elograph-json-result . Would you review and see how you like that? I didn't do all of the indentation.

**Comment by rchs819** [comment]
the branch looks good to me.

**Comment by rchs819** [comment]
@roy7 I didn't put your changes onto this PR.

Probably easier to merge https://github.com/gcp/leela-zero-server/tree/rchs819-enhancement/cache-elograph-json-result with `next`

**Comment by roy7** [comment]
I pulled https://github.com/gcp/leela-zero-server/tree/rchs819-enhancement/cache-elograph-json-result into next, which is smart enough to realize that means your PR is also pulled in, so it marked it as merged. Github is like magic.

**Comment by roy7** [comment]
Unless I did something wrong?

**Comment by roy7** [comment]
Nope, we're good. When I merged the local branch it also pulled in https://github.com/gcp/leela-zero-server/commit/deff778f4fecf5f31062d29cfd881f59b705e459 not just your commit.

**Pull request merged**
