### PR TITLE
Switch to t=1 for all self-play moves, i.e., randomcnt=999

### PR DESCRIPTION
**Pull request by Mardak**
r?@roy7 As per https://github.com/gcp/leela-zero-server/pull/77#issuecomment-386745083

### CODE REVIEW

**Comment by killerducky** [comment]
Sorry there are many conversations, I know AGZ does t=1 for first 30 and AZ does the entire game, and I'm in favor of switching. But what triggered us to switch? I think FB says they do it the AGZ way:

https://github.com/gcp/leela-zero/issues/1311#issuecomment-386742764

> When determining the next move of selfplay, it is t=1 for the first 30 moves and t=0 otherwise. However, when we train the model, we (almost) always use t=1 (i.e., distribution given by MCTS) to train the policy distribution. There is a switch --policy_distri_for_all to switch this on.

This sounds exactly like what AGZ and LZ currently do?

**Comment by gcp** [comment]
>But what triggered us to switch?

Well, the full story is in that thread, but basically, extremely summarized, ELF resigns when you ask it to play with handicap and We Do Not Like That Very Much.

**Comment by killerducky** [comment]
@gcp ok thanks for the answer. I have an interest in the reasons for changing it and also the results, because some people in the LZChess project suggest to move the opposite direction and reduce the temperature of training games in some way.

**Comment by gcp** [comment]
@killerducky Given that ELF basically shows how LZ would look with several more months of training, it's a very good time now for us to shake up things and see if we can get something better.

**Pull request merged**
