### PR TITLE
RSS feed (part 2)

### PR DESCRIPTION
**Pull request by rchs819**
Changes
- added network profile page
- improve RSS feed content and title

### CODE REVIEW

**Comment by rchs819** [comment]
### Network Profile Page 
Each RSS feed item will have links to profile page

#### Desktop
image


#### Mobile
image

**Comment by roy7** [comment]
@2ji3150 How are things now?

**Comment by 2ji3150** [comment]
@roy7  Follow on Feedly looks like the same. Or maybe the new style will be applied for the newer network only?

**Comment by rchs819** [comment]
http://zero.sjeng/rss?force=true should refresh the rss feed, but it seems not working.

Is this deployed to server? otherwise I need to find the bugs.

**Comment by roy7** [comment]
Oops! No it wasn't. Try now @2ji3150.

**Comment by 2ji3150** [comment]
Mine is still looks like this. I did remove and re-add it twice. Still don't know why.

https://imgur.com/a/Rj8Rm

If I typed the zero.sjeng.org/rss on the bowser it shows this
https://imgur.com/a/GxGY0

Does it correct or I miss something?

**Comment by 2ji3150** [comment]
Yes, Feedly now shows RSS feed title correctly. Thanks !

**Pull request merged**
