### PR TITLE
Add `gzip_hash`

### LINKED ISSUE #129: Add hash of gzip file to task requests?
See discussion here.

https://github.com/gcp/leela-zero/pull/1429#discussion_r188338729

It would allow autogtp to check for valid gzip file of a network hash without decompressing the file. If we calculate them on server as needed and store in a Map, we'd only need to do it once per gzip (per server restart) which is much less than once per autogtp startup/download.

### PR DESCRIPTION
**Pull request by rchs819**
fix #129

### CODE REVIEW

**Comment by roy7** [comment]
@marcocalignano This providing what you need?

**Comment by marcocalignano** [comment]
@roy7 I tried all the URL http://zero.sjeng.org/get-task/16 to http://zero.sjeng.org/get-task/19 but I didn't see the new option do I do something wrong?

**Comment by roy7** [comment]
@marcocalignano I was waiting for your feedback before merging. Oops. I'll merge it now.

**Comment by marcocalignano** [comment]
I still do not see it.

**Comment by Mardak** [comment]
@bood @rchs819 do you have measurements of how long awaiting for the hash takes? A quick look at get-task, which should be the most hit server endpoint is taking more than 1 second for every request.

**Comment by roy7** [comment]
It appears now.

**Comment by roy7** [comment]
http://zero.sjeng.org/get-task/19

Shows me:

{"cmd":"selfplay","hash":"e1d466aa129ef0d4b52288d1051570396c69cea50a3cd28b45ae6c524119e22c","required_client_version":"16","minimum_autogtp_version":"16","random_seed":"6718155938621713781","minimum_leelaz_version":"0.15","options_hash":"df715e","options":{"playouts":"0","visits":"3201","resignation_percent":"5","noise":"true","randomcnt":"999"},"**hash_gzip_hash**":"23c29bf777e446b5c3fb0e6e7fa4d53f15b99cc0c25798b70b57877b55bf1638"}

**Comment by marcocalignano** [comment]
@roy7  how can I test if a match works is there a special URL for matches? Can you "fake" one?

**Comment by marcocalignano** [comment]
@roy7 2 days of selfplay and no matches! I would like to test a match before I make the PR.
If you cannot make an URL with fake mathes maybe someone with a faster computer could test it for me.

**Comment by roy7** [comment]
Oops sorry. It didn't occur to me it can be hard to get a match randomly. Could I lure @mardak into a test?

**Comment by roy7** [comment]
Or send me your ip address on discord private messages and I will force feed you matches everytime possible.

**Comment by marcocalignano** [comment]
@roy7 I do not need many matches I just need one (if everything goes well). So maybe we can date a "cyber-date" where I can give you my IP (it changes every 6 hours) and you can feed my machine even with an old match.

**Pull request merged**
