### PR TITLE
Disallow submission if a random_seed is already used for a match

### PR DESCRIPTION
**Pull request by Mardak**
r?@roy7 / @rchs819 ? I believe this should reuse the existing index?

https://github.com/gcp/leela-zero-server/blob/453a6492c3757c4c7319697583a5226d27380706/mongodb.indexes#L17

This supersedes #65.

### CODE REVIEW

**Comment by rchs819** [comment]
Yes, it should reuse the index
```
db.match_games.explain().find({ 
  random_seed : 12150302704942565609, 
  $or: [
    { winnerhash: "2fb02cfe21d5de064176bad19dac5bd09ab4e773e5b8f7ce8f6990d135d6dc63", loserhash: "05b723d0c9e1c10abf18e9ba3e55c378de42e364cfe8a506d425f2af8ca204e8" },
    { winnerhash: "05b723d0c9e1c10abf18e9ba3e55c378de42e364cfe8a506d425f2af8ca204e8", loserhash: "2fb02cfe21d5de064176bad19dac5bd09ab4e773e5b8f7ce8f6990d135d6dc63" }
  ],
  option_hash: "df715e"
});
```
winningPlan is
```
"indexName" : "winnerhash_1_loserhash_1_options_hash_1__id_1"
```

**Comment by roy7** [comment]
@rchs819 Will you verify index use on this now that you downgraded to 3.4?

**Comment by Mardak** [comment]
Even if it isn't indexed, it would just mean the response to the client submitting a match would have to wait longer for the server to decide to reject or accept.

**Comment by rchs819** [comment]
```
 "indexName" : "winnerhash_1_loserhash_1_options_hash_1__id_1"
"version" : "3.4.14"
```

Index is used, but looks inefficient.
```
 "totalKeysExamined" : 7,
"totalDocsExamined" : 7,
```

**Comment by Mardak** [comment]
Is that because it's looking through 7 records that match the winner/loser/option hashes? I.e., there's 7 existing match games?

If so, it would need to scan through on average ~400/2 entries to determine that the random_seed doesn't exist. That's probably good enough and not worth adding a separate index that also includes random_seed.

**Comment by rchs819** [comment]
Will the `random_seed` be unique across **all** matches?

If so, it might be easier to build index just on `random_seed` column
```
db.match_games.createIndex(
  { "random_seed":1 }, 
  { "name":"random_seed_1","background":true}
); 
```
and query it by
```
db.match_games.explain('executionStats').find({
  random_seed : 12150302704942565609 
});
```

and do the `winnerhash`, `loserhash` & `option_hash` verification at node.js level.

**Comment by roy7** [comment]
Index added.

**Comment by Mardak** [comment]
Uh.. we don't guarantee that random_seed is unique for all match games. So an index on that might reject some unfortunate birthday paradox collision. Although, that should be extremely rare with 64 bits of randomness.

Should the query just findOne of the random_seed instead of with all the other attributes?

**Comment by Mardak** [comment]
I think this can land as is. With the new random_seed_1 having a non-unique index on random_seed will just make the query use that index, so the findOne should still check winner/loser hashes and options_hash in addition to random_seed. Duplicate random_seeds are allowed for different matches (assuming verification passes for the random_seed + other attributes).

**Pull request merged**
