### PR TITLE
Fix #176: Update cache when network2 got filled

### LINKED ISSUE #176: the website down?
http://zero.sjeng.org/match-games/5b2af76148e3e5462ada6825

Network Error (tcp_error)
--
A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems  preventing it from responding to requests. You may wish to try again at a  later time.
For assistance, contact your network support team

### PR DESCRIPTION
**Pull request by bood**
network2 of new match could be null resulting in it cannot be found by
db query (joining on network2)

also clear cache instead of inserting an item to make things simple
and stupid

### CODE REVIEW

**Comment by bood** [comment]
Yes, that would work too. I just feel keeping the code same for both network==null and network2!=null is easier to read. It's a minor difference anyway.

**Comment by roy7** [comment]
Yes it probably does keep it simple. I was just trying to think of a way to not lose your 'update the cache in place' trick. :)

If you want me to merge this as-is now I'll do so. Thanks.

**Comment by bood** [comment]
Yes, please merge and watch if we hit similar issue with this fix. We can do improvements later anyway. :-)

**Comment by roy7** [comment]
Ok logging to a new log file, can check tonight for any error messages. :)

**Comment by Mardak** [comment]
To be clear, the old approach had a memory leak as matches only ever got added and never removed. Practically, the number of added matches before the next restart wouldn't be too bad. In fact, there's been ~2000 matches so far, and keeping all those in memory probably isn't even comparable to loading in self-play training data. ;)

**Pull request merged**
