### PR TITLE
get-task: some comments on how I would implement the match distributi…

### PR DESCRIPTION
**Pull request by marcocalignano**
…on using the differnet threads data

### CODE REVIEW

**Comment by roy7** [comment]
I was thinking originally to save on performance I was going to store the fast clients only in ram. If server restarts then we need to rebuild that cache, but maybe some simple store/fetch to the database isn't a concern and then we have a persistent fastclients list we can cache up front at launch and only update as we go for "new" clients?

Since a random seed goes out on each query, my thought was to store a (IP, random_seed, start time) when we sent out a self play that doesn't have resign over-ridden to 0. Then when a self play comes back in, we look up the (IP, random_seed) and compare the start time to now(). If it's "fast enough", it goes into the fast clients.

This solves the concern of multiple threads on one IP where they sends in lots of games/hour but each individual game is really slow, since we're tracking IP,random_seed pairs and not just IP alone. Although if some threads are fast and some threads are slow, it'll still get tricked.

In your example you are storing the timex from the client with their IP address, so won't a client that has a single super fast thread still get flagged as a fast client? If we used the approach where a client is going to self-report their speed figure, I figured we wouldn't calculate fast clients ourselves at all. We'd just say "if timex is fast enough".

**Comment by marcocalignano** [comment]
>  In your example you are storing the timex from the client with their IP address, so won't a client that has a single super fast thread still get flagged as a fast client? 

I do this to eliminated from the fast client map where only IP are stored, but if a thread come with its own unique ID I select it from that so that the fast thread will be selected for a match but the slow threads no.

> If we used the approach where a client is going to self-report their speed figure, I figured we wouldn't calculate fast clients ourselves at all. We'd just say "if timex is fast enough".

Let say you have 100 threads in your table. If you fix "fast enough" to be 20 minutes per match and you have 3 match left on your queue in the worst case you take around 60 min time. 
If you sort the table and you select as "fast enough" the third value in the list. (let's say 3 mins) it will take worst case 9 min. So you wait to get the fastest threads before you deliver the games scaling the "fast enough" value dynamically (of course with some error margins).

**Comment by marcocalignano** [comment]
@roy7 Do you think you want to try the approch I suggested? I yes I can rebase PR #629 to the current /next so you can try it out. If you are sure you do not want to do it this way just let me know. (So I can delete the commit and stop rebasing in my repo ;) )

**Comment by roy7** [comment]
Whether it is this approach or something else, it's probably time to drop my fastclients code and overhaul it. Last hour had 90 match games and like 650 self play games. Clearly that's not optimal. :)

**Comment by roy7** [comment]
Of course it's also the fact the fancy system isn't sending matches out since we're about to fail and we have 32 matches running. Maybe I'm just impatient.

**Comment by Mardak** [comment]
Similar to the verification code encoded as part of `options_hash` that is sent back to the server when submitting a match, we can send a timestamp to each client as part of a selfplay task. When a selfplay is submitted along with the server provided options_hash or random_seed, the server can compute how long a given selfplay took. Assuming we want to find clients that have lower turnaround time, this would avoid issues where multiple instances / threads could appear fast if they all finished around the same time.

For example, if random_seed = 201805011234 representing an task created on 2018/05/01 12:34, and it was submitted to the server at 2018/05/01 12:44, we could estimate that this ip address can return a game in 10 minutes. For another client that submits 6 games with the same seed but at 2018/05/01 13:34, it would appear that the game latency is 1 hour even though the throughput is 6 games.

Of course, the encoded time doesn't need to be the full date and can include other actual random bits. The client doesn't need to be changed to handle the augmented random_seed. Although the server needs to be careful to overflow `GTP.h:extern std::uint64_t cfg_rng_seed;` (max 18,446,744,073,709,551,615 / 8 bytes / ~20 digit number). Although.. the number of minutes since UNIX epoch is 25,420,000, so just setting random_seed to 8 digits of random + 8 digits of minutes would probably be good and simple enough… (Although why set the time origin to UNIX epoch and not say.. leela zero network 0 2017-11-10 ;) and now it's about 250,000 minutes since then. But now we're in the weeds, and if we really wanted to cut down the number of bits dedicated to the timestamp, there's about 10,000 minutes in a week, so a 4-digit timestamp would probably be good enough to determine when in the last week a game was started to submitted, but there's now potential discrepancy if the task actually started over a week ago.)

**Comment by roy7** [comment]
Going to close this as we're merging https://github.com/gcp/leela-zero-server/pull/147 and it does some similar work but doesn't require client support or storing additional database info.

**Pull request closed without merging**
