### PR TITLE
Allow both is_test=1 and is_test=true for test matches

### PR DESCRIPTION
**Pull request by Mardak**
r?@roy7 Check for either string

### CODE REVIEW

**Comment by roy7** [comment]
Thanks, just a time saver for @gcp if future intuitive values are used instead of 'true'. ;)

**Comment by roy7** [comment]
I'll pop it live later today.

**Comment by gcp** [comment]
I'm pretty sure I'll be able to come up with new ways to get it wrong in the future.

**Comment by roy7** [comment]
Then we'll add those too. ;)

**Comment by Mardak** [comment]
Alternatively, I was thinking it should be more like html attributes where if it's set, it's active/true, and if it's missing, it's false. Although might want to rename it. And now we have the problem of remembering which flag to set. ;)

**Comment by roy7** [comment]
I've never seriously thought about taking it on, but someone could create a simple html interface for some of these things. Like an html form to toggle things or enter info and a filename prompt of the file to upload, then post it using that instead of curl.

Could also have basic html interface to tweak prior things, like add network names or toggle the is_test flag, whatever.

May not be worth the effort, I don't know, @gcp might be doing all of these uploads via command shells anyway.

**Comment by gcp** [comment]
Shell is fine for me.

**Comment by roy7** [comment]
@Mardak Hey think we should add your shell scripts to the repo?

**Pull request merged**
