### PR TITLE
Show test matches as a faded point on graphs

### PR DESCRIPTION
**Pull request by Mardak**
r? @roy7 Here's a screenshot with some fake json that has "TEST":

screen shot 2018-04-30 at 4 16 52 pm

### CODE REVIEW

**Comment by roy7** [comment]
Looks good. Any feedback from others before I merge it?

**Comment by Mardak** [comment]
You can update existing matches that have a test network:
```js
const MongoClient = require("mongodb").MongoClient;

(async () => {
    var db = await MongoClient.connect("mongodb://localhost/test");

    var networks = await db.collection("networks").find({
        $or: [
            { filters: 256, blocks: 20 },
            { filters: 128, blocks: 20 },
            { filters: 192, blocks: 10 },
            { hash: { $in: [
                "1e2b85cf611d5ede3f8d77ddc56a7bd79a7f1e51a647ddea428b92c00fdf2612", // best_v1
                "6615567eaa3adc8ea695682fcfbd7eaa3bb557d3720d2b61610b66006104050e.gz", // 128x10 net2net
            ] } }
        ]
    }).toArray();

    var hashes = networks.map(n => n.hash);
    console.log("Setting matches with network1 hashes as test:");
    console.log(hashes.join("\n"));

    await db.collection("matches").update({
        network1: { $in: hashes }
    }, {
        $set: { is_test: true }
    });

    db.close();
    console.log("Done");
})();
```

**Comment by Mardak** [comment]
Here's what the graph would look like showing more of the test networks:
screen shot 2018-05-01 at 9 58 58 am

**Comment by roy7** [comment]
Merged but many of the points you saw as plus signs, I don't on live server. Hmm.

**Comment by tychota** [comment]
@roy7 I cleared my cache and now it is ok

image

**Pull request merged**
